# -*- coding: utf-8 -*-
"""articles_db_relevancy_for166.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195orUYfuzoSPEtblhbRBzSzcGkGt7YGN
"""











# Enhanced Relevancy-Based Selection with Asset-Specific Preferences
import pandas as pd

print("="*80)
print("RELEVANCY-BASED ARTICLE SELECTION WITH ASSET PREFERENCES")
print("="*80)

# Load relevancy data
relevance_df = pd.read_csv('translated_articles_relevance.csv',
                           header=None,
                           names=['article_id', 'relevant', 'org_id', 'asset_id', 'incident_id'])

print(f"\n✓ Loaded {len(relevance_df)} relevancy records")
print(f"  TRUE (relevant): {(relevance_df['relevant'] == True).sum()}")
print(f"  FALSE (not relevant): {(relevance_df['relevant'] == False).sum()}")
print(f"  Unique assets: {relevance_df['asset_id'].nunique()}")

# Get only TRUE marks
true_marks = relevance_df[relevance_df['relevant'] == True].copy()

print("\n" + "="*80)
print("ASSET-SPECIFIC ARTICLE RELEVANCE")
print("="*80)

# Group by asset to see their preferences
for asset_id in sorted(true_marks['asset_id'].unique()):
    asset_articles = true_marks[true_marks['asset_id'] == asset_id]

    print(f"\n{'='*80}")
    print(f"ASSET {asset_id}")
    print(f"{'='*80}")
    print(f"Marked {len(asset_articles)} articles as relevant:")

    for idx, (_, row) in enumerate(asset_articles.iterrows(), 1):
        print(f"  {idx}. Article {row['article_id']} ✓")

# Calculate microweights PER ASSET
print("\n" + "="*80)
print("MICROWEIGHTS BY ASSET")
print("="*80)

asset_microweights = {}

for asset_id in relevance_df['asset_id'].unique():
    asset_data = relevance_df[relevance_df['asset_id'] == asset_id]

    # For this asset, create microweights for each article
    article_weights = {}

    for article_id in asset_data['article_id'].unique():
        article_relevance = asset_data[asset_data['article_id'] == article_id]
        is_relevant = (article_relevance['relevant'] == True).any()

        # Microweight: 2.0 if relevant to this asset, 1.0 if not
        weight = 2.0 if is_relevant else 1.0
        article_weights[article_id] = weight

    asset_microweights[asset_id] = article_weights

    # Show this asset's weights
    print(f"\nAsset {asset_id} Microweights:")
    relevant_articles = [aid for aid, w in article_weights.items() if w == 2.0]
    print(f"  Relevant articles (weight=2.0): {len(relevant_articles)}")
    print(f"  Not relevant (weight=1.0): {len(article_weights) - len(relevant_articles)}")

    if relevant_articles:
        print(f"  Prioritized articles: {relevant_articles[:5]}")  # Show first 5

# Create a pivot table showing article relevance across assets
print("\n" + "="*80)
print("ARTICLE RELEVANCE MATRIX (Article × Asset)")
print("="*80)

# Create pivot: rows=articles, columns=assets, values=TRUE/FALSE
pivot = true_marks.pivot_table(
    index='article_id',
    columns='asset_id',
    values='relevant',
    aggfunc='any',
    fill_value=False
)

print(f"\nShowing which assets marked which articles as relevant:")
print(f"{'Article ID':<15}", end='')
for asset_id in sorted(pivot.columns):
    print(f"Asset_{asset_id:<6}", end='')
print()
print("-" * (15 + 12 * len(pivot.columns)))

for article_id in pivot.index:
    print(f"{article_id:<15}", end='')
    for asset_id in sorted(pivot.columns):
        mark = "✓" if pivot.loc[article_id, asset_id] else "·"
        print(f"{mark:<12}", end='')
    print()

# Summary statistics
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

print("\nArticle popularity (how many assets marked it relevant):")
article_popularity = true_marks.groupby('article_id').size().sort_values(ascending=False)

for article_id, count in article_popularity.items():
    assets = true_marks[true_marks['article_id'] == article_id]['asset_id'].tolist()
    print(f"  Article {article_id}: Relevant to {count} asset(s) → {assets}")

print("\nAsset selectivity (how many articles each asset marked relevant):")
asset_selectivity = true_marks.groupby('asset_id').size().sort_values(ascending=False)

for asset_id, count in asset_selectivity.items():
    articles = true_marks[true_marks['asset_id'] == asset_id]['article_id'].tolist()
    print(f"  Asset {asset_id}: Marked {count} articles as relevant → {articles[:3]}{'...' if count > 3 else ''}")

print("\n" + "="*80)
print("✓ COMPLETE")
print("="*80)
print("\nEach asset has personalized microweights!")
print("Articles marked TRUE get weight=2.0, others get weight=1.0")





